export type LessonFamily = "repetition" | "structure" | "drama" | "principles";

export type Lesson = {
  id: string;
  name: string;
  family: LessonFamily;
  definition: string;
  example: string;
  attribution: string;
  drillPrompt: string;
};

export const FAMILY_LABEL: Record<LessonFamily, string> = {
  repetition: "Repetition",
  structure: "Structure",
  drama: "Drama",
  principles: "Principles",
};

export const LESSONS: Lesson[] = [
  {
    id: "anaphora",
    name: "Anaphora",
    family: "repetition",
    definition: "Repeat the same words at the start of successive clauses.",
    example: "We shall fight on the beaches, we shall fight on the landing grounds...",
    attribution: "Winston Churchill",
    drillPrompt: "Describe a goal you refuse to give up on. Open three sentences the same way.",
  },
  {
    id: "epistrophe",
    name: "Epistrophe",
    family: "repetition",
    definition: "Repeat the same words at the END of successive clauses.",
    example: "...of the people, by the people, for the people.",
    attribution: "Abraham Lincoln",
    drillPrompt: "Explain who your work is really for. End three clauses with the same phrase.",
  },
  {
    id: "anadiplosis",
    name: "Anadiplosis",
    family: "repetition",
    definition: "End one clause with a word, begin the next with it.",
    example: "Fear leads to anger. Anger leads to hate.",
    attribution: "Yoda",
    drillPrompt: "Trace a chain of cause and effect in your work, linking each step by its last word.",
  },
  {
    id: "alliteration",
    name: "Alliteration",
    family: "repetition",
    definition: "Repeat an initial consonant sound across nearby words.",
    example: "Let us go forth to lead the land we love.",
    attribution: "John F. Kennedy",
    drillPrompt: "Pitch your favourite tool in three sentences with a repeated opening sound.",
  },
  {
    id: "polysyndeton",
    name: "Polysyndeton",
    family: "repetition",
    definition: "Stack conjunctions to build momentum.",
    example: "And the rain descended, and the floods came, and the winds blew.",
    attribution: "Matthew 7:25",
    drillPrompt: "Describe your busiest day using 'and' between every action.",
  },
  {
    id: "diacope",
    name: "Diacope",
    family: "repetition",
    definition: "Repeat a word with one or two words in between.",
    example: "Bond. James Bond.",
    attribution: "Ian Fleming",
    drillPrompt: "Introduce yourself so your name or your role lands twice.",
  },
  {
    id: "tricolon",
    name: "Tricolon",
    family: "structure",
    definition: "Three parallel items — the most satisfying number in speech.",
    example: "I came, I saw, I conquered.",
    attribution: "Julius Caesar",
    drillPrompt: "Summarise your last project in exactly three parallel phrases.",
  },
  {
    id: "antithesis",
    name: "Antithesis",
    family: "structure",
    definition: "Set two opposite ideas in a balanced frame.",
    example: "Ask not what your country can do for you...",
    attribution: "John F. Kennedy",
    drillPrompt: "Contrast how you used to work with how you work now, in one balanced sentence.",
  },
  {
    id: "chiasmus",
    name: "Chiasmus",
    family: "structure",
    definition: "Mirror the structure of a clause in reverse order.",
    example: "Never let a fool kiss you, or a kiss fool you.",
    attribution: "Mardy Grothe",
    drillPrompt: "Write a mirrored sentence about learning and teaching.",
  },
  {
    id: "parallelism",
    name: "Parallelism",
    family: "structure",
    definition: "Give similar ideas the same grammatical shape.",
    example: "Reading maketh a full man; conference a ready man; writing an exact man.",
    attribution: "Francis Bacon",
    drillPrompt: "List three responsibilities in identical grammatical form.",
  },
  {
    id: "asyndeton",
    name: "Asyndeton",
    family: "structure",
    definition: "Drop the conjunctions for speed and urgency.",
    example: "Duty, honour, country.",
    attribution: "Douglas MacArthur",
    drillPrompt: "Deliver an urgent status update with no conjunctions at all.",
  },
  {
    id: "climax",
    name: "Climax",
    family: "structure",
    definition: "Arrange items in ascending intensity.",
    example: "...neither death, nor life, nor angels, nor principalities...",
    attribution: "Romans 8:38",
    drillPrompt: "Describe a challenge, escalating each detail beyond the last.",
  },
  {
    id: "prolepsis",
    name: "Prolepsis",
    family: "structure",
    definition: "Raise the objection yourself, then answer it.",
    example: "You'll say it's too expensive. It isn't — here's why.",
    attribution: "Classical rhetoric",
    drillPrompt: "Pitch an idea and pre-empt the strongest objection to it.",
  },
  {
    id: "enumeratio",
    name: "Enumeratio",
    family: "structure",
    definition: "Break a claim into its concrete parts.",
    example: "It costs you time, money, focus, and sleep.",
    attribution: "Classical rhetoric",
    drillPrompt: "Justify a decision by listing its concrete components.",
  },
  {
    id: "metaphor",
    name: "Metaphor",
    family: "drama",
    definition: "Say one thing IS another to transfer its meaning.",
    example: "All the world's a stage.",
    attribution: "Shakespeare",
    drillPrompt: "Explain your job to a child using one sustained metaphor.",
  },
  {
    id: "simile",
    name: "Simile",
    family: "drama",
    definition: "Compare with 'like' or 'as' to make the abstract visible.",
    example: "Life is like a box of chocolates.",
    attribution: "Forrest Gump",
    drillPrompt: "Describe a hard week using three vivid similes.",
  },
  {
    id: "hyperbole",
    name: "Hyperbole",
    family: "drama",
    definition: "Deliberate exaggeration for emphasis.",
    example: "I've told you a million times.",
    attribution: "Everyday speech",
    drillPrompt: "Tell a funny story about a small annoyance, exaggerating on purpose.",
  },
  {
    id: "rhetorical-question",
    name: "Rhetorical Question",
    family: "drama",
    definition: "Ask a question whose answer you supply — or which needs none.",
    example: "If not us, who? If not now, when?",
    attribution: "Ronald Reagan",
    drillPrompt: "Open a persuasive pitch with a question your audience can't dodge.",
  },
  {
    id: "personification",
    name: "Personification",
    family: "drama",
    definition: "Give human agency to an idea or object.",
    example: "The city never sleeps.",
    attribution: "Common usage",
    drillPrompt: "Describe your biggest obstacle as if it were a person in the room.",
  },
  {
    id: "understatement",
    name: "Understatement",
    family: "drama",
    definition: "Deliberately downplay for dry force.",
    example: "'Tis but a scratch.",
    attribution: "Monty Python",
    drillPrompt: "Recount a stressful moment while playing it down completely.",
  },
  {
    id: "small-sturdy-words",
    name: "Small, Sturdy Words",
    family: "principles",
    definition: "Short concrete words carry more weight than long abstract ones.",
    example: "'We choose to go to the Moon.' — nine words, eight of them short.",
    attribution: "Peggy Noonan",
    drillPrompt: "Explain a complex idea from your field using only short, concrete words.",
  },
  {
    id: "pause",
    name: "The Pause",
    family: "principles",
    definition: "Silence before a key phrase makes it land harder than volume ever will.",
    example: "Pause. Then: 'That changed everything.'",
    attribution: "Public speaking craft",
    drillPrompt: "Tell a short story, marking with '...' where you'd pause for effect.",
  },
  {
    id: "specificity",
    name: "Specificity",
    family: "principles",
    definition: "One concrete detail beats five general claims.",
    example: "Not 'we improved things' — 'we cut checkout from 40 seconds to 9.'",
    attribution: "Craft principle",
    drillPrompt: "Describe an accomplishment using at least three exact numbers or details.",
  },
  {
    id: "audience-first",
    name: "Audience First",
    family: "principles",
    definition: "Open with what matters to them, not with what matters to you.",
    example: "'Here's what this saves your team' before 'here's what I built.'",
    attribution: "Craft principle",
    drillPrompt: "Pitch your work to an executive, leading with their concern, not yours.",
  },
];

export const LESSONS_BY_FAMILY = (family: LessonFamily) => LESSONS.filter((l) => l.family === family);
